apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-final
  labels:
    app: nodeapp-final
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp-final
  template:
    metadata:
      labels:
        app: nodeapp-final
    spec:
      containers:
      - name: nodeapp
        image: nodeapp:final
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
