name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./app

      - name: Run Semgrep code scan
        run: |
          pip install semgrep
          semgrep --config auto ./app

      - name: Install Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install wget -y
          wget -qO- https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh
          sudo mv ./bin/trivy /usr/local/bin/
          export PATH=$PATH:/usr/local/bin
          trivy -v

      - name: Build Docker image
        run: docker build -t nodeapp-secure -f docker/Dockerfile .

      - name: Scan Docker image
        run: trivy image --exit-code 1 --severity HIGH,CRITICAL nodeapp-secure

      - name: Push image if secure
        if: success()
        run: echo "âœ… Image passed all security checks"

